// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(LessonsDbContext))]
    [Migration("20240603192152_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uid");

                    b.Property<ushort>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<Guid>("LessonStateTypeUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("lesson_state_type_uid");

                    b.Property<Guid>("LessonTypeUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("lesson_type_uid");

                    b.Property<ushort>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("starting_time");

                    b.HasKey("Uid")
                        .HasName("lesson__pk");

                    b.HasIndex("LessonStateTypeUid");

                    b.HasIndex("LessonTypeUid");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LessonStateType", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Uid")
                        .HasName("lesson_state_type__pk");

                    b.ToTable("lesson_state_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LessonStudent", b =>
                {
                    b.Property<Guid>("LessonUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("lesson_uid");

                    b.Property<Guid>("StudentUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("student_uid");

                    b.HasKey("LessonUid", "StudentUid")
                        .HasName("lesson_student__pk");

                    b.HasIndex("StudentUid");

                    b.ToTable("lesson_student", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LessonType", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Uid")
                        .HasName("lesson_type__pk");

                    b.ToTable("lesson_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("uid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Uid")
                        .HasName("student__pk");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Domain.Entities.LessonStateType", "StateType")
                        .WithMany()
                        .HasForeignKey("LessonStateTypeUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.LessonType", "Type")
                        .WithMany()
                        .HasForeignKey("LessonTypeUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.LessonStudent", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonStudents")
                        .HasForeignKey("LessonUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("StudentLessons")
                        .HasForeignKey("StudentUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonStudents");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
